### PR TITLE
fix: add package.path, package.cpath only for lazy.nvim

### PR DESCRIPTION
**Pull request by Freed-Wu**

### CODE REVIEW

**Comment by black-desk** [comment]
Why this is a fix?

**Comment by Freed-Wu** [comment]
If only lazy.nvim need to add these paths, perhaps we can avoid add them for other users to keep a clean package.path.

**Comment by black-desk** [comment]
I mean that it make more sense to be a "refact" than a "fix"

**Comment by Freed-Wu** [comment]
OK, done.

**Pull request merged**
